#!/bin/bash

ssh -n mtprd01         'hostname; df -m |grep cms'
ssh -n mtprd02         'hostname; df -m |grep cms'
ssh -n mtprd03         'hostname; df -m |grep cms'
ssh -n mtprd04         'hostname; df -m |grep cms'
ssh -n mtprd05         'hostname; df -m |grep cms'
ssh -n mtprd06         'hostname; df -m |grep cms'
ssh -n mtprd07         'hostname; df -m |grep cms'
ssh -n mtprd08         'hostname; df -m |grep cms'
ssh -n mtprd09         'hostname; df -m |grep cms'
ssh -n mtprd10         'hostname; df -m |grep cms'
ssh -n mtprd11         'hostname; df -m |grep cms'
ssh -n mtprd12         'hostname; df -m |grep cms'
ssh -n ussclpdapcmsl01 'hostname; df -m |grep cms'
ssh -n ussclpdapcmsl02 'hostname; df -m |grep cms'
ssh -n ussclpdapcmsl03 'hostname; df -m |grep cms'
ssh -n ussclpdapcmsl04 'hostname; df -m |grep cms'
ssh -n ussclpdapcmsl05 'hostname; df -m |grep cms'
ssh -n ussclpdapcmsl06 'hostname; df -m |grep cms'
ssh -n ussclpdapcmsl07 'hostname; df -m |grep cms'
ssh -n ussclpdapcmsl08 'hostname; df -m |grep cms'
ssh -n ussclpdapcmsl09 'hostname; df -m |grep cms'
ssh -n ussclpdapcmsl10 'hostname; df -m |grep cms'
ssh -n ussclpdapcmsl11 'hostname; df -m |grep cms'
ssh -n ussclpdapcmsl12 'hostname; df -m |grep cms'
ssh -n neucmslinux		 'hostname; df -m |grep cms'
ssh -n ussclsdcmslnx01 'hostname; df -m |grep cms'
