#!/bin/bash

ssh -n mtprd01         "hostname; free -tm"
ssh -n mtprd02         "hostname; free -tm"
ssh -n mtprd03         "hostname; free -tm"
ssh -n mtprd04         "hostname; free -tm"
ssh -n mtprd05         "hostname; free -tm"
ssh -n mtprd06         "hostname; free -tm"
ssh -n mtprd07         "hostname; free -tm"
ssh -n mtprd08         "hostname; free -tm"
ssh -n mtprd09         "hostname; free -tm"
ssh -n mtprd10         "hostname; free -tm"
ssh -n mtprd11         "hostname; free -tm"
ssh -n mtprd12         "hostname; free -tm"
ssh -n ussclpdapcmsl01 "hostname; free -tm"
ssh -n ussclpdapcmsl02 "hostname; free -tm"
ssh -n ussclpdapcmsl03 "hostname; free -tm"
ssh -n ussclpdapcmsl04 "hostname; free -tm"
ssh -n ussclpdapcmsl05 "hostname; free -tm"
ssh -n ussclpdapcmsl06 "hostname; free -tm"
ssh -n ussclpdapcmsl07 "hostname; free -tm"
ssh -n ussclpdapcmsl08 "hostname; free -tm"
ssh -n ussclpdapcmsl09 "hostname; free -tm"
ssh -n ussclpdapcmsl10 "hostname; free -tm"
ssh -n ussclpdapcmsl11 "hostname; free -tm"
ssh -n ussclpdapcmsl12 "hostname; free -tm"
ssh -n neucmslinux		 "hostname; free -tm"
ssh -n ussclsdcmslnx01 "hostname; free -tm"
